set.seed(123) #Standardizes the numbers generated by rnorm; see Chapter 5

N <- 100 #Number of participants; graduate students

# OG lines
M <- 100
X <- rnorm(N, 175, 7) #IV; hours since dawn
M <- 0.7*X + rnorm(N, 100, 30) #Suspected mediator; coffee consumption 

# Erli lines
M <- 100
X <-matrix( rnorm(N*M,mean=50,sd=7), N, M) 
M <- 0.7*X[,1] + rnorm(N, 100, 30) #Suspected mediator; coffee consumption 

# compute model
Y <- 0.4*M + rnorm(N, 0, 5) #DV; wakefulness
Meddata <- data.frame(X, M, Y)

#################################################
#################### Mediation Package method ####

fitM <- lm(M ~ X,     data=Meddata) #IV on M; Hours since dawn predicting coffee consumption
fitM
fitY <- lm(Y ~ X + M, data=Meddata) #IV and M on DV; Hours since dawn and coffee predicting wakefulness
fitY

fitM <- lm(M ~ X,     data=Meddata) #IV on M; Hours since dawn predicting coffee consumption
fitM
fitY <- lm(Y ~ X + M, data=Meddata) #IV and M on DV; Hours since dawn and coffee predicting wakefulness
fitY

library(gvlma) #Testing Model Assumptions 

gvlma(fitM) #data is positively skewed; could log transform (see Chap. 10 on assumptions)
gvlma(fitY)